data:extend{
    {
        type            = "selection-tool",
        name            = "ScanArea-tool",
        subgroup        = "tool",
        icon            = "__base__/graphics/icons/satellite.png",
        icon_size       = 64,
        flags           = { "not-stackable", "only-in-cursor", "spawnable" },
        hidden          = true,
        stack_size      = 1,
        select          = {
            mode            = "nothing",
            cursor_box_type = "copy",
            border_color    = { 0.0, 0.5, 1.0 },
        },
        alt_select      = {
            mode            = "nothing",
            cursor_box_type = "copy",
            border_color    = { 1.0, 0.0, 0.0 },
        },
    },
    {
        type            = "shortcut",
        name            = "ScanArea-shortcut",
        action          = "spawn-item",
        item_to_spawn   = "ScanArea-tool",
        technology_to_unlock = "rocket-silo",
        icon            = "__ScanArea__/graphics/telescope-32.png",
        icon_size       = 32,
        small_icon      = "__ScanArea__/graphics/telescope-24.png",
        small_icon_size = 24,
    },
    {
        type            = "custom-input",
        name            = "ScanArea-input",
        key_sequence    = "",
        action          = "spawn-item",
        item_to_spawn   = "ScanArea-tool",
    },
}
